# Generated by Django 4.2 on 2024-09-17 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Название")),
                ("model", models.CharField(max_length=30, verbose_name="Модель")),
                ("release_date", models.DateField(verbose_name="Дата выхода")),
            ],
            options={
                "verbose_name_plural": "Продукт",
            },
        ),
        migrations.CreateModel(
            name="Chain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя звена")),
                ("contacts", models.JSONField(verbose_name="Контакты")),
                (
                    "debt_to_supplier",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Задолженность"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="retail.chain",
                        verbose_name="Поставщик",
                    ),
                ),
                ("products", models.ManyToManyField(to="retail.product")),
            ],
            options={
                "verbose_name_plural": "Звено",
            },
        ),
    ]
