# Generated by Django 4.2 on 2024-09-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chain",
            name="contacts",
            field=models.JSONField(blank=True, null=True, verbose_name="Контакты"),
        ),
        migrations.AlterField(
            model_name="chain",
            name="debt_to_supplier",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Задолженность",
            ),
        ),
    ]
