# Generated by Django 4.2 on 2024-09-17 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("retail", "0003_contact_remove_chain_products_chain_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chain",
            name="contacts",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="retail.contact",
                verbose_name="Контакты",
            ),
        ),
        migrations.RemoveField(
            model_name="chain",
            name="products",
        ),
        migrations.AddField(
            model_name="chain",
            name="products",
            field=models.ManyToManyField(to="retail.product"),
        ),
    ]
