# Generated by Django 4.2 on 2024-09-17 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("retail", "0005_alter_chain_contacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chain",
            name="contacts",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="retail.contact",
                verbose_name="Контакты",
            ),
        ),
    ]
