# Generated by Django 4.2 on 2024-09-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail", "0006_alter_chain_contacts"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="chain_line",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Завод", "Завод изготовитель"),
                    ("Сеть", "Торговая сеть"),
                    ("ИП", "Индивидуальный предприниматель"),
                ],
                max_length=20,
                null=True,
                verbose_name="Звено",
            ),
        ),
    ]
