# Generated by Django 4.2 on 2024-09-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail", "0007_contact_chain_line"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="chain_line",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Завод", "Завод изготовитель"),
                    ("Сеть", "Торговая сеть"),
                    ("ИП", "Индивидуальный предприниматель"),
                ],
                max_length=20,
                null=True,
                verbose_name="Звено в цепи",
            ),
        ),
    ]
