# Generated by Django 4.2 on 2024-09-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail", "0009_chain_is_factory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chain",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Имя звена"
            ),
        ),
    ]
